[default]
    locale = "en-us"

    [default.extend-words]
        criticals = "criticals"

[files]
    extend-exclude = ["*_cache", ".env", ".env.secrets", ".venv", "CHANGELOG.md", "_site", "static"]
