[default]
    locale = "en-us"

    [default.extend-words]
        # nd     = "nd"     # Used in the context of '2nd'

[files]
    extend-exclude = ["*_cache", ".env", ".env.secrets", ".venv", "CHANGELOG.md", "_site", "static"]
