allowed_types = [
    "build",
    "bump",
    "chore",
    "ci",
    "docs",
    "feat",
    "fix",
    "perf",
    "refactor",
    "revert",
    "style",
    "test",
]
ignore_author_re = "(dependabot|renovate)"
line_length = 500
merge_commit = false
style = "conventional"
subject_capitalized = false
subject_length = 60
